### ISSUE TITLE
[FetchIt!] SCHUNK machine model shoudn't have the cylinder inserted

### ISSUE THREAD

**Issue by umhan35** [fetchrobotics/fetch_gazebo#82] opened 2019-04-23 19:30 UTC
@moriarty Our team just know that we need to insert the gear inside the whole of the SCHUNK machine. In simulation, there is a half yellow half black cylinder inserted and should be removed.

@RDaneelOlivav  We tried to use Blender to remove the cylindar from `shunk_machine_lathe_centered.dae` but the main.launch file won't launch probably because the pose also needs to be updated?

In sim:
![schunk station (sim)](https://user-images.githubusercontent.com/3271612/56609755-e2deb480-65db-11e9-9dbb-2b1c22c71646.png)

In the arena:
![schunk station](https://user-images.githubusercontent.com/3271612/56609757-e5410e80-65db-11e9-8037-33af952629bc.png)

**Comment by moriarty** [comment] 2019-04-23 20:50
@ajzeller Could you open up the model in Solid Works and remove the object from the lathe?

Then we can give a new model to @RDaneelOlivav , unless @RDaneelOlivav is able to do this directly.

**Comment by ajzeller** [comment] 2019-04-23 21:19
@moriarty here is the URDF with the object removed:

[schunk_machine_URDF_4-23-19.zip](https://github.com/fetchrobotics/fetch_gazebo/files/3109649/schunk_machine_URDF_4-23-19.zip)

![image](https://user-images.githubusercontent.com/11982359/56616666-c2f6c300-65d2-11e9-823f-408cd3d7e903.png)

**Comment by moriarty** [comment] 2019-04-23 22:56
Thanks @ajzeller !

Actually could you add one more thing?

The real machine has boards around it, then we can fix #61 and this issue at the same time.
Don't worry about the logo, just the boards for now as they should be their for the teams to make and test their mapping and localization.

**Comment by ajzeller** [comment] 2019-04-23 23:28
@moriarty yep here you go:

[schunk_machine_URDF_4-23-19_v2.zip](https://github.com/fetchrobotics/fetch_gazebo/files/3109949/schunk_machine_URDF_4-23-19_v2.zip)

![image](https://user-images.githubusercontent.com/11982359/56622416-dad74280-65e4-11e9-810a-bb67c8c5b020.png)

**Comment by RDaneelOlivav** [comment] 2019-04-24 07:46
Ok great! I'll put it in the task list to do ;)
Also I havent integrated yet the SHUNK actions into the machine, but I think thats for another time.

**Comment by moriarty** [comment] 2019-04-24 21:09
This photo was requested by @banerjs 
![IMG_8006](https://user-images.githubusercontent.com/55676/56693966-81314f80-669a-11e9-95d3-e8112e6cdd35.JPG)

**Comment by moriarty** [comment] 2019-04-25 21:41
@RDaneelOlivav just as a clarification re:

> Also I haven't integrated yet the SCHUNK actions into the machine, but I think that's for another time.

The action **_only_** opens and closes the Schunk **chuck** not the whole door. The Door, is on sliders, which the teams can push on the handle to slide open and closed.

**Comment by ben-fido** [comment] 2019-04-28 00:34
The above colored images of the Schunk Machine are from a CAD program.

We downloaded the .zip file and opened the 3D model.  
It looks like this:  
<img src="https://i.imgur.com/HtzdpfH.png" width="200">
It is one single solid part.  
This would be a regression in functionality, because @RDaneelOlivav already did a great job to build the current model:  It has multiple parts, color texture, the door slides shut and the spindle can rotate by publishing a ROS msg command.

.

Have a look at this Collada file:  
`fetch_gazebo/fetchit_challenge/models/shunk_machine/meshes/shunk_machine_lathe_centered.dae`
<img src="https://i.imgur.com/WgsVeZ4.png" width="200">

We just need someone to open this model and bore out the tube.

Still, the chuck jaws do not open and close. I will make a new ticket for that.

.

**Comment by RDaneelOlivav** [comment] 2019-05-03 18:31
Ok I've pushed an update of the chunk machine ( #89), with new updated action server decoupled from simulation or real thing. Also updated the model, colours, and added chuck open and close system, with integration with the action server. Now if you spawn the Shunk machine it should just be there operational.
To use it just publish the goal in the goal topic.

**Comment by moriarty** [comment] 2019-06-05 18:50
Fixed with #89

**Closed as completed by moriarty** 2019-06-05 18:50 UTC
Labels: bug, FetchIt!
